using UnityEngine;
using System.Collections;

public enum NormalSummonType
{
	NORMAL_SUMMON_10_MIN=1,
	NORMAL_SUMMON_30_MIN=2,
	NORMAL_SUMMON_2_HOUR=3,
	NORMAL_SUMMON_6_HOUR=4,
	NORMAL_SUMMON_12_HOUR=5
}

public enum SacrificeSummonType
{
	SACRI_SUMMON_LOW_LEVEL=1,
	SACRI_SUMMON_ATTR_ADJUST=2,
	SACRI_SUMMON_HIGH_LEVEL=3
}

